# emtools_data_plot: Gnuplot plotting commands
# Command line:
# "emtools_data_plot smallmod_NLCG_000.dat smallmod_NLCG_005.dat smallmod_NLCG_010.dat -k Iter_0,Iter_5,Iter10 -o smallmod -w p_pt_5_ps_0.4,l,l -keep"
#
# Gnuplot header
#
# Default line/symbol color sequence
c1="black"
c2="medium-blue" 
c3="dark-red"
c4="dark-green"
# Subplot settings (default, can be overwritten)
sx=0.99; sy=0.44 # data subplot size (multiplot: set size)
# REAL-data subplot
# "0xffffdd" # background color example
x1=0.05; y1=0.520 # origin (graph) coordinates
# IMAG-data subplot
# "0xffffee" # background color example
x2=0.05; y2=0.023 # origin (graph) coordinates
#
# Output terminal settings
#set terminal png medium linewidth 1.3
#set terminal jpeg medium linewidth 1.3
set lmargin 2; set rmargin 0; set tmargin 0; set bmargin 0 # margins
# Axis format
set format "%g"
set key
set grid
# Data plotting style
set style data lines
# Logo image: if present, insert into each plot page
sxlogo=0.24; sylogo=0.082 # size of logo image
xlogo=0.85; ylogo=-0.0785 # origin (graph) of logo image
#
# Gnuplot linetypes:
#
lw=1.5
set linetype 1 lc rgb "black" lw lw
set linetype 2 lc rgb "dark-violet"   lw lw
set linetype 3 lc rgb "blue"          lw lw
set linetype 4 lc rgb "sea-green"     lw lw
set linetype 5 lc rgb "dark-red"      lw lw
set linetype 6 lc rgb "dark-cyan"     lw lw
set linetype 7 lc rgb "mediumpurple3" lw lw
set linetype 8 lc rgb "pink"       lw lw
set linetype cycle 8
#
flogo="N/A"
# Data input file#1: smallmod_NLCG_000.dat (reference data)
# Data input file#2: smallmod_NLCG_005.dat
# Data input file#3: smallmod_NLCG_010.dat

#
# Begin of plot commands generated by emtools_data_plot (system: linux)
#
set terminal postscript portrait color background "white" solid font "Courier" 13
set output "smallmod.ps"
# BEGIN Additional (optional user-defined) Gnuplot header
# N/A
#  END  Additional (optional user-defined) Gnuplot header

# Plot data file:
d="smallmod.dat"

set log y
# **** Index=0, T=4sec (f=0.25Hz), Component=ZXY, Ndata=272 ****
set multiplot; set size sx,sy
set title "Tx#1: T=4sec (f=0.25Hz), Rx-comp=ZXY" noenhanced
unset xlabel; set ylabel "ZXY(Real) [V/m]/[A/m]" noenhanced
# Subplot#1) RE-data
set key font "Courier,12" noenhanced
set origin x1,y1; set size sx,sy
plot d i 0 u 1:(abs($5)) title "Iter_0" with p pt 5 ps 0.4 lt 1, d i 0 u 1:(abs($7)) title "Iter_5" with l lt 2, d i 0 u 1:(abs($9)) title "Iter10" with l lt 3
unset title
set xlabel "Rx#" noenhanced
set ylabel "ZXY(Imag) [V/m]/[A/m]" noenhanced
# Subplot#2) IM-data
set key font "Courier,12" noenhanced
set origin x2,y2; set size sx,sy
plot d i 0 u 1:(abs($6)) title "Iter_0" with p pt 5 ps 0.4 lt 1, d i 0 u 1:(abs($8)) title "Iter_5" with l lt 2, d i 0 u 1:(abs($10)) title "Iter10" with l lt 3
unset multiplot

# **** Index=1, T=4sec (f=0.25Hz), Component=ZYX, Ndata=272 ****
set multiplot; set size sx,sy
set title "Tx#2: T=4sec (f=0.25Hz), Rx-comp=ZYX" noenhanced
unset xlabel; set ylabel "ZYX(Real) [V/m]/[A/m]" noenhanced
# Subplot#1) RE-data
set key font "Courier,12" noenhanced
set origin x1,y1; set size sx,sy
plot d i 1 u 1:(abs($5)) title "Iter_0" with p pt 5 ps 0.4 lt 1, d i 1 u 1:(abs($7)) title "Iter_5" with l lt 2, d i 1 u 1:(abs($9)) title "Iter10" with l lt 3
unset title
set xlabel "Rx#" noenhanced
set ylabel "ZYX(Imag) [V/m]/[A/m]" noenhanced
# Subplot#2) IM-data
set key font "Courier,12" noenhanced
set origin x2,y2; set size sx,sy
plot d i 1 u 1:(abs($6)) title "Iter_0" with p pt 5 ps 0.4 lt 1, d i 1 u 1:(abs($8)) title "Iter_5" with l lt 2, d i 1 u 1:(abs($10)) title "Iter10" with l lt 3
unset multiplot
